export const NAVO_DATA = {
  categories: ['Politics', 'Economy', 'World', 'Technology', 'Sport', 'Culture', 'Investigations', 'Regions'],

  breaking: [
    'BREAKING: UN Security Council meets emergency session over escalating tensions in the Strait of Hormuz',
    'Markets: Dow Jones drops 2.3% amid Federal Reserve rate decision uncertainty',
    'World leaders gather in Geneva for climate emergency summit — live coverage',
    'Exclusive: leaked documents reveal undisclosed lobbying ties to three ministers',
  ],

  articles: [
    {
      id: 1, slug: 'geopolitical-shift-new-world-order', category: 'World',
      title: 'The Geopolitical Shift That Nobody Saw Coming: A New World Order Is Taking Shape',
      subtitle: 'Three years after the last major crisis, analysts warn that the foundations of global power are quietly being rewritten — and most governments are unprepared.',
      excerpt: 'Three years after the last major crisis, analysts warn that the foundations of global power are quietly being rewritten.',
      author: { name: 'Elena Marchetti', role: 'Senior International Correspondent' },
      date: 'April 26, 2026', readTime: '8 min read',
      imageCaption: "World leaders at last month's closed-door summit in Geneva.",
      tags: ['Geopolitics', 'NATO', 'China', 'USA', 'Diplomacy'], featured: true,
      body: [
        { type: 'p', content: 'For decades, the post-Cold War liberal order held firm — fraying at the edges, yes, but recognizable in its essential architecture. That architecture is now crumbling, according to a new wave of geopolitical analysis that points not to any single dramatic rupture, but to a slow-motion realignment that has been building since 2020.' },
        { type: 'p', content: 'The signs are everywhere, if you know where to look. Trade agreements signed quietly without American involvement. Military exercises conducted across new axes of partnership. Currency swaps that bypass the dollar. Each individually could be dismissed as noise; together, they compose a signal.' },
        { type: 'quote', content: 'We are not watching the end of American hegemony — we are watching the end of the assumption that hegemony can be permanent. That is a different, and more important, shift.', attribution: 'Dr. Aisha Nakamura, Brookings Institution' },
        { type: 'p', content: 'What makes this moment different from previous periods of geopolitical turbulence is the simultaneity of the pressures. Technology competition, climate stress, demographic imbalance, and debt-driven fiscal strain are all arriving at the same moment, in the same governments, demanding resolution with the same limited pool of political capital.' },
        { type: 'p', content: 'Institutions built for another era — the IMF, the WTO, the UN Security Council — are visibly struggling to process the new reality. Reform proposals circulate and stall. Vetoes multiply. Emergency sessions are called and end without communiqués.' },
        { type: 'quote', content: "The multilateral system was built on assumptions that no longer hold. That doesn't mean it will collapse — but it does mean it will look very different in ten years.", attribution: 'Prof. James Okafor, London School of Economics' },
        { type: 'p', content: 'None of this is cause for pure alarm. Multipolar systems have governed the world before, sometimes badly and sometimes better than what replaced them. But the transition is inherently unstable — and instability has costs.' },
      ],
    },
    {
      id: 2, slug: 'ai-regulation-global-race', category: 'Technology',
      title: 'The AI Regulation Race: Who Gets to Write the Rules for the Most Powerful Technology in History?',
      excerpt: "Europe moves first, China moves fastest, and the United States can't decide what it wants. The global AI governance gap is widening.",
      author: { name: 'Tom Vasquez', role: 'Technology Editor' },
      date: 'April 25, 2026', readTime: '6 min read', tags: ['AI', 'Regulation', 'Technology', 'Policy'],
      body: [
        { type: 'p', content: "The race to regulate artificial intelligence has become the most consequential policy contest of the decade — and it's happening in slow motion, in committee rooms and parliamentary sessions far from public view." },
        { type: 'p', content: "Three distinct models are now competing for global adoption. The European Union's risk-tiered framework, now in its second revision. China's security-first approach, which prioritizes state oversight and content control. And the United States' sector-by-sector patchwork, which satisfies nobody and is increasingly seen as an abdication." },
        { type: 'quote', content: 'Whoever writes the rules for AI will effectively set the terms of the 21st-century economy. That\'s why this fight matters far beyond tech policy circles.', attribution: 'Prof. Maya Chen, MIT Technology Policy Lab' },
        { type: 'p', content: 'The Brussels Effect — the tendency for EU regulation to become a de facto global standard — may be the most significant force in play. Companies building for the European market build once, then deploy everywhere with the same guardrails. It is regulation by default.' },
      ],
    },
    {
      id: 3, slug: 'central-bank-digital-currencies', category: 'Economy',
      title: 'Central Bank Digital Currencies: The Quiet Revolution That Could Reshape Every Wallet on Earth',
      excerpt: 'More than 130 countries are developing digital currencies. The implications for privacy, monetary policy, and financial inclusion are enormous.',
      author: { name: 'Priya Sharma', role: 'Economics Correspondent' },
      date: 'April 25, 2026', readTime: '7 min read', tags: ['CBDC', 'Finance', 'Economy', 'Digital'],
      body: [
        { type: 'p', content: "The world's central banks are, almost without public notice, engineering the most significant transformation of money in a century. More than 130 countries — representing 98% of global GDP — are now in some stage of CBDC development." },
        { type: 'p', content: 'The appeal is obvious to monetary authorities: programmable money that can be distributed instantly, tracked precisely, and recalled if misused. For governments, it offers unprecedented visibility into economic activity. For citizens, it presents a more complex bargain.' },
        { type: 'quote', content: 'A CBDC without strong privacy protections is not a digital currency. It is a financial surveillance system with a friendly name.', attribution: 'Dr. Lukas Weber, European Central Bank Advisory Group' },
      ],
    },
    {
      id: 4, slug: 'climate-tipping-points-2026', category: 'World',
      title: 'Scientists Identify Five New Climate Tipping Points — and Two Have Already Been Crossed',
      excerpt: 'A landmark study published this week in Nature offers the most comprehensive mapping of climate system thresholds to date.',
      author: { name: 'Lena Brandt', role: 'Science & Environment Reporter' },
      date: 'April 24, 2026', readTime: '5 min read', tags: ['Climate', 'Science', 'Environment'],
      body: [
        { type: 'p', content: 'A new study redraws the map of climate risk with unsettling precision. Published in Nature this week, the research identifies fourteen planetary tipping points — thresholds beyond which self-reinforcing change becomes effectively irreversible.' },
        { type: 'p', content: "Five of these tipping points are newly identified by the research team. Two, the authors confirm with high confidence, have already been crossed: the collapse of the Greenland Ice Sheet's southern dome, and the die-off of the Amazon's eastern basin." },
        { type: 'quote', content: 'We are no longer talking about preventing tipping points. We are talking about how many more we can avoid, and how quickly we can adapt to those already triggered.', attribution: 'Prof. Astrid Lindqvist, Stockholm Resilience Centre' },
      ],
    },
    {
      id: 5, slug: 'opposition-leader-interview', category: 'Politics',
      title: '"We Are Ready to Govern": Opposition Leader Breaks Silence in Exclusive Interview',
      excerpt: "After months of internal restructuring, the opposition's new leader speaks candidly about policy, coalition prospects, and the path to power.",
      author: { name: 'Marco Bellini', role: 'Political Editor' },
      date: 'April 24, 2026', readTime: '9 min read', tags: ['Politics', 'Interview', 'Election'],
      body: [
        { type: 'p', content: 'She arrived without entourage, settled into the chair across from me, and immediately ordered water instead of coffee. It was, I would come to realize, a characteristic choice — deliberate, unpretentious, slightly disarming.' },
        { type: 'p', content: 'The opposition has spent three years rebuilding after its worst electoral defeat in a generation. The new leader, who took over fourteen months ago, has spent most of that time refusing interviews. This is the first extended conversation she has granted to any international outlet.' },
        { type: 'quote', content: 'We lost because we forgot who we were for. That clarity — about people, not about power — is what we\'ve spent these months rebuilding.', attribution: 'Opposition Leader, exclusive interview with NAVO' },
      ],
    },
    {
      id: 6, slug: 'streaming-wars-new-phase', category: 'Culture',
      title: 'The Streaming Wars Enter a New Phase — and the Casualties Are Quality and Choice',
      excerpt: 'As consolidation accelerates and subscriber growth plateaus, the golden age of peak TV may be giving way to something considerably more corporate.',
      author: { name: 'Sofia Reyes', role: 'Culture Critic & Media Analyst' },
      date: 'April 23, 2026', readTime: '6 min read', tags: ['Culture', 'Streaming', 'Media'],
      body: [
        { type: 'p', content: "The streaming boom was supposed to be permanent. It wasn't. After years of exponential subscriber growth, the major platforms are now fighting over a market that has effectively stopped expanding in their most valuable territories." },
        { type: 'p', content: 'The response has been predictable and disheartening: consolidation, price increases, password-sharing crackdowns, and — most visibly — a retreat from the kind of ambitious, expensive, singular programming that defined the peak TV era.' },
        { type: 'quote', content: "We're entering the cable era of streaming. Less experimentation, more franchise. Less risk, more algorithm. The creative window may be closing.", attribution: 'Sarah Okonkwo, TV critic and media analyst' },
      ],
    },
    {
      id: 7, slug: 'youth-unemployment-europe', category: 'Economy',
      title: 'Youth Unemployment in Europe Hits 15-Year High as Automation Reshapes Entry-Level Work',
      excerpt: 'The jobs that once served as stepping stones — data entry, customer service, basic analysis — are disappearing faster than alternatives emerge.',
      author: { name: 'Priya Sharma', role: 'Economics Correspondent' },
      date: 'April 23, 2026', readTime: '7 min read', tags: ['Economy', 'Youth', 'Automation', 'Europe'],
      body: [
        { type: 'p', content: "The economic data has been accumulating for two years. Now it's impossible to ignore. Youth unemployment across the EU has reached 18.4% — the highest since 2011 — and the structural causes are fundamentally different from those that drove the post-financial-crisis spike." },
        { type: 'p', content: 'Then, the problem was demand. Companies weren\'t hiring because economies were contracting. Now, the problem is structural substitution. The entry-level jobs that generations of young workers used as economic footholds — administrative roles, data processing, customer service, basic financial analysis — are being automated faster than equivalent roles emerge.' },
      ],
    },
    {
      id: 8, slug: 'semiconductor-supply-chain', category: 'Technology',
      title: 'Inside the Semiconductor Supply Chain: Why the Next Chip Shortage Is Already Being Built',
      excerpt: 'Despite billions in government investment and new factory openings, structural vulnerabilities remain — and experts say a crisis is a matter of when, not if.',
      author: { name: 'Tom Vasquez', role: 'Technology Editor' },
      date: 'April 22, 2026', readTime: '8 min read', tags: ['Technology', 'Semiconductors', 'Supply Chain'],
      body: [
        { type: 'p', content: 'The fabs are being built. The subsidies have been disbursed. The press releases have been drafted and released. And yet, according to a growing chorus of industry insiders and independent analysts, the semiconductor supply chain remains dangerously fragile.' },
        { type: 'p', content: 'The problem is not capacity — it is concentration. Despite the CHIPS Act, the EU Chips Act, and equivalent programmes in Japan, South Korea and India, the manufacture of the most advanced semiconductors — those below 5 nanometres — remains almost entirely confined to a single facility in Taiwan.' },
        { type: 'quote', content: 'We have diversified the middle of the supply chain. We have not diversified the most critical node. Everything else is theatre.', attribution: 'Dr. Kenji Nakamura, semiconductor policy analyst' },
      ],
    },
    {
      id: 9, slug: 'sports-governance-crisis', category: 'Sport',
      title: 'The Governance Crisis at the Heart of International Sport: A Special Report',
      excerpt: 'From football to athletics, the institutions that govern global sport are facing simultaneous crises of legitimacy, corruption, and relevance.',
      author: { name: 'Marco Bellini', role: 'Political Editor' },
      date: 'April 22, 2026', readTime: '11 min read', tags: ['Sport', 'Governance', 'FIFA', 'IOC'],
      body: [
        { type: 'p', content: 'International sport is governed by some of the least accountable institutions on earth. They are private organisations with public power, extracting enormous value from national identities and civic passions while answering to almost no external authority.' },
        { type: 'p', content: 'FIFA, the IOC, World Athletics, the UCI: the list of governing bodies currently under formal investigation, facing legal challenge, or managing active leadership scandals is longer than it has been at any point in the modern era.' },
      ],
    },
    {
      id: 10, slug: 'eastern-europe-investment-boom', category: 'Economy',
      title: "Eastern Europe's Quiet Investment Boom: What the Numbers Say and What They Don't",
      excerpt: 'Foreign direct investment into Poland, Romania and the Baltic states hit record highs last year. The story behind the headline is more complicated.',
      author: { name: 'Elena Marchetti', role: 'Senior International Correspondent' },
      date: 'April 21, 2026', readTime: '6 min read', tags: ['Economy', 'Eastern Europe', 'Investment'],
      body: [
        { type: 'p', content: 'The figures are striking. Foreign direct investment into Poland, Romania, Estonia, Latvia and Lithuania combined reached €94 billion last year — a record, and an increase of 31% over the previous year. The headline tells a story of a region arriving at its economic moment.' },
        { type: 'p', content: 'But figures always need context. A significant portion of the investment surge is driven by military-adjacent industries, logistics infrastructure tied to the ongoing conflict in Ukraine, and EU cohesion funds repackaged as private investment. Underlying greenfield investment — the kind that creates long-term employment — grew by a more modest 12%.' },
      ],
    },
    {
      id: 11, slug: 'investigative-offshore-networks', category: 'Investigations',
      title: 'Offshore Networks: How Public Infrastructure Money Disappears Into Private Accounts',
      excerpt: 'A 14-month investigation by NAVO and nine international partners traces the path of €2.3 billion in EU development funds.',
      author: { name: 'Elena Marchetti', role: 'Senior International Correspondent' },
      date: 'April 20, 2026', readTime: '15 min read', tags: ['Investigations', 'Corruption', 'EU', 'Finance'],
      body: [
        { type: 'p', content: 'The money left Brussels with clear instructions. What happened next took us 14 months to reconstruct. Working with nine investigative partners across six countries, NAVO can today publish the most detailed account yet of how EU development funds are systematically diverted through a network of shell companies, opaque foundations, and offshore accounts.' },
        { type: 'p', content: 'The mechanism is elegant in its simplicity. Infrastructure contracts are awarded to companies that exist only on paper, subcontracted to real firms at a fraction of the declared price, with the difference extracted to accounts in jurisdictions that do not share financial information.' },
        { type: 'quote', content: 'This is not opportunistic corruption. This is institutionalised theft with legal camouflage. The structures were built specifically to survive scrutiny.', attribution: 'Anti-corruption prosecutor, speaking on condition of anonymity' },
      ],
    },
    {
      id: 12, slug: 'urban-heat-islands', category: 'Regions',
      title: 'Urban Heat Islands: How City Planning Decisions Made in the 1970s Are Now Killing People',
      excerpt: 'The legacy of parking-lot urbanism, concrete sprawl, and green-space neglect is visible in mortality statistics during every summer heatwave.',
      author: { name: 'Lena Brandt', role: 'Science & Environment Reporter' },
      date: 'April 19, 2026', readTime: '7 min read', tags: ['Regions', 'Cities', 'Climate', 'Urban'],
      body: [
        { type: 'p', content: 'In the summer of 2025, seventeen people died in a mid-sized European city during a week-long heatwave. The city had a population of 340,000, a functioning health system, and — unlike many of the places that feature in climate mortality statistics — no shortage of resources.' },
        { type: 'p', content: 'What it had, in abundance, was concrete. Parking lots covering land that once held trees. Roads widened in the 1970s at the expense of avenue greenery. Housing estates built to maximise unit count, not thermal comfort. The city was, in the language of urban climatology, a heat trap — and it had been built that way, decision by decision, across five decades.' },
      ],
    },
    {
      id: 13, slug: 'nato-eastern-flank-expansion', category: 'World',
      title: "NATO's Eastern Flank: Why the Alliance Is Quietly Repositioning Forces Across Four Countries",
      excerpt: 'Beyond the headlines, a structural shift in NATO deployments signals a new strategic posture that will define European security for a generation.',
      author: { name: 'Elena Marchetti', role: 'Senior International Correspondent' },
      date: 'April 18, 2026', readTime: '8 min read', tags: ['NATO', 'World', 'Geopolitics', 'Europe'],
      body: [{ type: 'p', content: 'The redeployments have been gradual, deliberate, and largely unreported.' }],
    },
    {
      id: 14, slug: 'eu-ai-act-implementation', category: 'Technology',
      title: "One Year In: How Companies Are Actually Implementing the EU AI Act — and What's Going Wrong",
      excerpt: 'The landmark regulation is now in force. The compliance reality looks very different from what regulators anticipated.',
      author: { name: 'Tom Vasquez', role: 'Technology Editor' },
      date: 'April 17, 2026', readTime: '7 min read', tags: ['AI', 'EU', 'Regulation', 'Technology'],
      body: [{ type: 'p', content: 'Implementation has been messier than anyone predicted.' }],
    },
    {
      id: 15, slug: 'imf-global-debt-warning', category: 'Economy',
      title: 'IMF Issues Starkest Global Debt Warning in a Decade: What It Means for Ordinary People',
      excerpt: "The Fund's spring outlook paints a sobering picture of sovereign debt sustainability across both advanced and emerging economies.",
      author: { name: 'Priya Sharma', role: 'Economics Correspondent' },
      date: 'April 16, 2026', readTime: '6 min read', tags: ['IMF', 'Debt', 'Economy', 'Finance'],
      body: [{ type: 'p', content: "The numbers are not new. The IMF's tone is." }],
    },
    {
      id: 16, slug: 'far-right-municipal-surge', category: 'Politics',
      title: 'The Far-Right Municipal Surge: How Local Elections Are Becoming the New Front Line of European Politics',
      excerpt: 'City halls from Stockholm to Palermo are shifting rightward, creating governance laboratories for movements preparing for national power.',
      author: { name: 'Marco Bellini', role: 'Political Editor' },
      date: 'April 15, 2026', readTime: '9 min read', tags: ['Politics', 'Europe', 'Elections', 'Far-right'],
      body: [{ type: 'p', content: 'The town square was always political. It has rarely been this contested.' }],
    },
    {
      id: 17, slug: 'arctic-shipping-routes', category: 'World',
      title: 'The Arctic Is Open for Business: New Shipping Routes Are Redrawing the Map of Global Trade',
      excerpt: 'As sea ice retreats, the Northern Sea Route is becoming commercially viable year-round — and triggering a geopolitical race that few saw coming.',
      author: { name: 'Elena Marchetti', role: 'Senior International Correspondent' },
      date: 'April 14, 2026', readTime: '7 min read', tags: ['Arctic', 'Trade', 'World', 'Climate'],
      body: [{ type: 'p', content: 'The Kremlin called it an opportunity. The Canadians called it a threat. Both were right.' }],
    },
    {
      id: 18, slug: 'quantum-computing-finance', category: 'Technology',
      title: 'Quantum Computing Comes to Finance: Banks Are Running the First Real-World Experiments',
      excerpt: 'JPMorgan, Deutsche Bank and three others have quietly moved quantum applications from the lab to live trading infrastructure.',
      author: { name: 'Tom Vasquez', role: 'Technology Editor' },
      date: 'April 13, 2026', readTime: '8 min read', tags: ['Quantum', 'Finance', 'Technology', 'Banking'],
      body: [{ type: 'p', content: "The first use case wasn't what anyone expected." }],
    },
    {
      id: 19, slug: 'european-cinema-renaissance', category: 'Culture',
      title: 'A European Cinema Renaissance? Why Foreign-Language Films Are Dominating the Global Box Office',
      excerpt: 'For the first time in 30 years, non-English-language films hold three of the top five global box office spots. Something has changed.',
      author: { name: 'Sofia Reyes', role: 'Culture Critic & Media Analyst' },
      date: 'April 12, 2026', readTime: '5 min read', tags: ['Culture', 'Cinema', 'Film', 'Europe'],
      body: [{ type: 'p', content: 'The subtitle is no longer a barrier. It may now be a selling point.' }],
    },
    {
      id: 25, slug: 'permafrost-methane-crisis', category: 'World',
      title: 'The Permafrost Timebomb: New Data Shows Methane Release 40% Above Previous Estimates',
      excerpt: 'An international monitoring network has captured readings that force a fundamental reassessment of near-term warming trajectories.',
      author: { name: 'Lena Brandt', role: 'Science & Environment Reporter' },
      date: 'April 11, 2026', readTime: '6 min read', tags: ['Climate', 'Science', 'Environment', 'World'],
      body: [{ type: 'p', content: 'The data arrived quietly, as the most alarming data tends to do.' }],
    },
    {
      id: 26, slug: 'gig-economy-legal-battles', category: 'Economy',
      title: "The Gig Economy's Legal Reckoning: Landmark Court Rulings Are Reshaping Work Across Three Continents",
      excerpt: 'Courts in the UK, Brazil and India have issued rulings in the past 90 days that could force the reclassification of millions of workers.',
      author: { name: 'Priya Sharma', role: 'Economics Correspondent' },
      date: 'April 10, 2026', readTime: '7 min read', tags: ['Economy', 'Gig', 'Labour', 'Law'],
      body: [{ type: 'p', content: "Three courts, three continents, three months. The gig economy's legal walls are closing." }],
    },
    {
      id: 27, slug: 'disinformation-election-playbook', category: 'Investigations',
      title: 'The Disinformation Playbook: How Coordinated Campaigns Are Being Built Six Months Before Each Election',
      excerpt: 'A joint investigation by NAVO and partner organisations has mapped the infrastructure behind election-related disinformation in seven countries.',
      author: { name: 'Investigations Desk', role: 'Investigations Team' },
      date: 'April 9, 2026', readTime: '14 min read', tags: ['Investigations', 'Disinformation', 'Elections', 'Democracy'],
      body: [{ type: 'p', content: 'The campaign begins long before the voting starts.' }],
    },
    {
      id: 28, slug: 'green-hydrogen-reality-check', category: 'Economy',
      title: 'Green Hydrogen: The Reality Check the Energy Transition Needed',
      excerpt: 'After years of hype, the economics of green hydrogen are becoming clearer — and more complicated than the original pitch.',
      author: { name: 'Priya Sharma', role: 'Economics Correspondent' },
      date: 'April 8, 2026', readTime: '6 min read', tags: ['Energy', 'Economy', 'Climate', 'Technology'],
      body: [{ type: 'p', content: 'The promise was simple. The physics was always less so.' }],
    },
    {
      id: 29, slug: 'social-media-mental-health-regulation', category: 'Technology',
      title: 'Tech Platforms and Teen Mental Health: The Regulatory Tipping Point Has Arrived',
      excerpt: 'After years of voluntary commitments and weak oversight, governments across five countries have passed legally binding age-verification and content rules.',
      author: { name: 'Tom Vasquez', role: 'Technology Editor' },
      date: 'April 7, 2026', readTime: '6 min read', tags: ['Technology', 'Mental Health', 'Regulation', 'Social Media'],
      body: [{ type: 'p', content: 'The companies knew this was coming. They lobbied hard to delay it.' }],
    },
  ],

  mostRead: [1, 11, 5, 8, 3],
  latest: [29, 28, 27, 26, 25, 19, 18, 17, 16],

  authors: [
    {
      slug: 'elena-marchetti',
      name: 'Elena Marchetti', role: 'Senior International Correspondent',
      specialization: 'Geopolitics & Diplomacy', location: 'Brussels, Belgium',
      articles: 247, yearsActive: 14, articleCount: 247, photoId: 'photo-1494790108377-be9c29b29330',
      bio: "Elena Marchetti has spent 14 years reporting from the world's most consequential diplomatic corridors. A graduate of the London School of Economics and Sciences Po Paris, she covered the 2016 Brexit referendum, the collapse of the Iran nuclear talks, and the formation of the AUKUS alliance. Her investigative series on European defense procurement won the European Press Prize in 2023. She speaks Italian, French, English, and functional Arabic.",
      social: { twitter: '@emarchetti', linkedin: 'elena-marchetti' },
      categories: ['World', 'Politics', 'Investigations'],
    },
    {
      slug: 'tom-vasquez',
      name: 'Tom Vasquez', role: 'Technology Editor',
      specialization: 'AI, Tech Policy & Cybersecurity', location: 'San Francisco, USA',
      articles: 183, yearsActive: 9, photoId: 'photo-1507003211169-0a1dd7228f2d',
      bio: "Tom Vasquez leads NAVO's technology desk from San Francisco, where he has embedded himself in the Silicon Valley ecosystem for nearly a decade. Before joining NAVO, he was a senior reporter at Wired and a research fellow at the Stanford Internet Observatory. His coverage of AI regulation has been cited in three separate Congressional hearings and translated into 11 languages.",
      social: { twitter: '@tomvasquez_tech' },
      categories: ['Technology'],
    },
    {
      slug: 'priya-sharma',
      name: 'Priya Sharma', role: 'Economics Correspondent',
      specialization: 'Macro-economics, Finance & Trade', location: 'London, UK',
      articles: 312, yearsActive: 17, photoId: 'photo-1573496359142-b8d87734a5a2',
      bio: 'With 17 years of financial journalism behind her, Priya Sharma is one of Europe\'s most respected economics correspondents. She holds an MSc in Economics from the University of Edinburgh and has reported from the World Economic Forum in Davos every year since 2012. Her book "The Debt Horizon" (2021) became a bestseller across six countries. She previously worked at the Financial Times and Reuters.',
      social: { twitter: '@priyasharma_eco', linkedin: 'priya-sharma-economics' },
      categories: ['Economy'],
    },
    {
      slug: 'marco-bellini',
      name: 'Marco Bellini', role: 'Political Editor',
      specialization: 'European Politics & Electoral Systems', location: 'Rome, Italy',
      articles: 198, yearsActive: 11, photoId: 'photo-1472099645785-5658abf4ff4e',
      bio: 'Marco Bellini has covered Italian and European politics since the Monti government, developing deep expertise in coalition dynamics and electoral systems. His analysis of the 2024 European Parliament elections was republished by 40 media organisations across the continent. He graduated from La Sapienza University and completed a journalism fellowship at Reuters in London. He is also a regular commentator on RAI and Euronews.',
      social: { twitter: '@marcobellini_eu' },
      categories: ['Politics'],
    },
    {
      slug: 'lena-brandt',
      name: 'Lena Brandt', role: 'Science & Environment Reporter',
      specialization: 'Climate Science, Environment & Urban Policy', location: 'Berlin, Germany',
      articles: 156, yearsActive: 8, photoId: 'photo-1438761681033-6461ffad8d80',
      bio: "Lena Brandt joined NAVO after four years at Der Spiegel's science desk, where she built a reputation for translating complex climate science into accessible, urgent narratives. She has reported from COP summits in Dubai, Glasgow, and Sharm el-Sheikh, and her feature on permafrost methane emissions was shortlisted for the Deutsche Umweltpreis. She holds a degree in Environmental Sciences from Humboldt University.",
      social: { twitter: '@lenabrandt_sci' },
      categories: ['World', 'Regions'],
    },
    {
      slug: 'sofia-reyes',
      name: 'Sofia Reyes', role: 'Culture Critic & Media Analyst',
      specialization: 'Media, Arts, Society & Digital Culture', location: 'Madrid, Spain',
      articles: 204, yearsActive: 12, photoId: 'photo-1531746020798-e6953c6e8e04',
      bio: 'Sofia Reyes writes about the intersection of culture, technology, and power — exploring how media shapes public consciousness and how entertainment industries are being restructured by streaming, algorithms, and geopolitics. Her criticism has appeared in El País, The Guardian, and Frieze. She is currently writing a book about the political economy of attention, and lectures part-time at the Universidad Autónoma de Madrid.',
      social: { twitter: '@sofiareyes_cultura', linkedin: 'sofia-reyes-media' },
      categories: ['Culture'],
    },
  ],
}

export function getFullAuthor(name) {
  return NAVO_DATA.authors.find(a => a.name === name) || null
}
